#test to run when there is a PR to the develop branch
name: Develop PR tests
on:
    pull_request:
        branches:
            - develop

    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Node setup
              uses: actions/setup-node@v4 
              with:
                node-version-file: ".nvmrc"
                cache: "npm"


            - name: lint and build test
              run: npm ci && npm run lint && npm run build
            