# credits: https://royserg.hashnode.dev/bearboard-4-devops
# repo: https://github.com/Royserg/bear-board/tree/main

name: Modify updater with latest release

on: 
  workflow_dispatch:
  workflow_call:
    secrets:
      TAG:
        description: 'A token passed from the caller workflow'
        required: true
      GIST_ID:
        description: 'id of updater gist'
        required: true

jobs:
  modify-updater-gist:
    permissions:
      contents: write
    name: Modify updater.json gist
    runs-on: ubuntu-latest
    steps:
      - name: update download urls and signatures for updater gist
        uses: actions/github-script@v7
        env:
          updater_gist_id: ${{ secrets.GIST_ID }}
        with:
          github-token: ${{ secrets.TAG }}
          script: |

            const { data } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const { name, body, published_at, assets } = data;
     
            const latest_url = assets[0].browser_download_url;
            const latest_data = await github.request(latest_url).then( ({data}) => {
                return JSON.parse(new TextDecoder().decode(data))
            });
     
    
            const notes = body.replace(/ *\([^)]*\)|#|\) */g, '');
            latest_data.notes = notes;
      
        
            try {
                await github.rest.gists.update({
                    gist_id: process.env.updater_gist_id,
                    files: {
                        "updater.json": {
                            content: JSON.stringify(latest_data, null, 2)
                        }
                    }
                });
            } catch (error) {
                console.error('Failed to update gist:', error);
            }
